apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator
  namespace: p2p-dht
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coordinator
  template:
    metadata:
      labels:
        app: coordinator
    spec:
      nodeSelector:
        building: a
      containers:
      - name: coordinator
        image: us-central1-docker.pkg.dev/resilientp2p-492916/resilientp2p/coordinator:a250c05
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: p2p-common-config
        - secretRef:
            name: p2p-auth-token
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: coordinator
  namespace: p2p-dht
spec:
  selector:
    app: coordinator
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
