apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer-a1
  namespace: p2p-dht
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peer-a1
  template:
    metadata:
      labels:
        app: peer-a1
        building: a
    spec:
      nodeSelector:
        building: a
      containers:
      - name: peer
        image: us-central1-docker.pkg.dev/resilientp2p-492916/resilientp2p/dht-peer:v1
        ports:
        - containerPort: 7000
          protocol: TCP
        - containerPort: 6000
          protocol: UDP
        envFrom:
        - configMapRef:
            name: p2p-common-config
        - secretRef:
            name: p2p-auth-token
        env:
        - name: PEER_ID
          value: "peer-a1"
        - name: LOCATION_ID
          value: "Building-A"
        - name: PEER_GROUP
          value: "professors"
        - name: PEER_HOST
          value: "peer-a1.p2p-dht.svc.cluster.local"
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        readinessProbe:
          httpGet:
            path: /health
            port: 7000
          initialDelaySeconds: 8
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 7000
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: peer-a1
  namespace: p2p-dht
spec:
  selector:
    app: peer-a1
  ports:
  - name: http
    port: 7000
    targetPort: 7000
    protocol: TCP
  - name: dht
    port: 6000
    targetPort: 6000
    protocol: UDP
